[package]
authors = ["thedavidmeister", "thedavidmeister@gmail.com"]
edition = "2021"
name = "test_wasm_foo"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_wasm_foo"

[dependencies]
hdi = "0.3.2-beta-rc.0"
hdk = "0.2.2-beta-rc.0"
serde = "1"
