name: "flake_update"

on:
  workflow_dispatch:
  schedule:
    # At 7:00am on Monday
    - cron: "0 7 * * 1"

jobs:
  flake_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          install_url: https://releases.nixos.org/nix/nix-2.20.4/install
          extra_nix_config: |
            experimental-features = flakes nix-command

      - name: Flake update
        run: |
          nix flake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update flake.lock"
          title: "Update flake.lock"
          body: "This PR updates the flake.lock file."
          branch: "update-flake-lock"
          branch-suffix: "short-commit-hash"
          base: "main"
